apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-rollouts-config
  labels:
    app.kubernetes.io/component: rollouts-controller
    app.kubernetes.io/name: argo-rollouts
    app.kubernetes.io/part-of: argo-rollouts
