apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: rollouts-demo-route
spec:
  http:
    - name: rollouts-demo
      match:
        paths:
          - /*
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
        hosts:
          - rollouts-demo.apisix.local
      backends:
        - serviceName: rollouts-demo-stable
          servicePort: 80
          weight: 100
        - serviceName: rollouts-demo-canary
          servicePort: 80
          weight: 0
