// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"

	v1alpha1 "github.com/argoproj/argo-rollouts/pkg/apis/rollouts/v1alpha1"
)

// MetricsRecorder is an autogenerated mock type for the MetricsRecorder type
type MetricsRecorder struct {
	mock.Mock
}

// EmitRolloutDuration provides a mock function with given fields: ds
func (_m *MetricsRecorder) EmitRolloutDuration(ds *v1alpha1.RolloutDurationStatus) {
	_m.Called(ds)
}

// IncAnalysisRunReconcile provides a mock function with given fields: ar, duration
func (_m *MetricsRecorder) IncAnalysisRunReconcile(ar *v1alpha1.AnalysisRun, duration time.Duration) {
	_m.Called(ar, duration)
}

// IncError provides a mock function with given fields: namespace, name, kind
func (_m *MetricsRecorder) IncError(namespace string, name string, kind string) {
	_m.Called(namespace, name, kind)
}

// IncExperimentReconcile provides a mock function with given fields: ex, duration
func (_m *MetricsRecorder) IncExperimentReconcile(ex *v1alpha1.Experiment, duration time.Duration) {
	_m.Called(ex, duration)
}

// IncRolloutReconcile provides a mock function with given fields: rollout, duration
func (_m *MetricsRecorder) IncRolloutReconcile(rollout *v1alpha1.Rollout, duration time.Duration) {
	_m.Called(rollout, duration)
}

// Remove provides a mock function with given fields: namespace, name, kind
func (_m *MetricsRecorder) Remove(namespace string, name string, kind string) {
	_m.Called(namespace, name, kind)
}

// NewMetricsRecorder creates a new instance of MetricsRecorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricsRecorder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricsRecorder {
	mock := &MetricsRecorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
