/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	rolloutsv1alpha1 "github.com/argoproj/argo-rollouts/pkg/apis/rollouts/v1alpha1"
	scheme "github.com/argoproj/argo-rollouts/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// AnalysisTemplatesGetter has a method to return a AnalysisTemplateInterface.
// A group's client should implement this interface.
type AnalysisTemplatesGetter interface {
	AnalysisTemplates(namespace string) AnalysisTemplateInterface
}

// AnalysisTemplateInterface has methods to work with AnalysisTemplate resources.
type AnalysisTemplateInterface interface {
	Create(ctx context.Context, analysisTemplate *rolloutsv1alpha1.AnalysisTemplate, opts v1.CreateOptions) (*rolloutsv1alpha1.AnalysisTemplate, error)
	Update(ctx context.Context, analysisTemplate *rolloutsv1alpha1.AnalysisTemplate, opts v1.UpdateOptions) (*rolloutsv1alpha1.AnalysisTemplate, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*rolloutsv1alpha1.AnalysisTemplate, error)
	List(ctx context.Context, opts v1.ListOptions) (*rolloutsv1alpha1.AnalysisTemplateList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *rolloutsv1alpha1.AnalysisTemplate, err error)
	AnalysisTemplateExpansion
}

// analysisTemplates implements AnalysisTemplateInterface
type analysisTemplates struct {
	*gentype.ClientWithList[*rolloutsv1alpha1.AnalysisTemplate, *rolloutsv1alpha1.AnalysisTemplateList]
}

// newAnalysisTemplates returns a AnalysisTemplates
func newAnalysisTemplates(c *ArgoprojV1alpha1Client, namespace string) *analysisTemplates {
	return &analysisTemplates{
		gentype.NewClientWithList[*rolloutsv1alpha1.AnalysisTemplate, *rolloutsv1alpha1.AnalysisTemplateList](
			"analysistemplates",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *rolloutsv1alpha1.AnalysisTemplate { return &rolloutsv1alpha1.AnalysisTemplate{} },
			func() *rolloutsv1alpha1.AnalysisTemplateList { return &rolloutsv1alpha1.AnalysisTemplateList{} },
		),
	}
}
