/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	rolloutsv1alpha1 "github.com/argoproj/argo-rollouts/pkg/apis/rollouts/v1alpha1"
	scheme "github.com/argoproj/argo-rollouts/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// RolloutsGetter has a method to return a RolloutInterface.
// A group's client should implement this interface.
type RolloutsGetter interface {
	Rollouts(namespace string) RolloutInterface
}

// RolloutInterface has methods to work with Rollout resources.
type RolloutInterface interface {
	Create(ctx context.Context, rollout *rolloutsv1alpha1.Rollout, opts v1.CreateOptions) (*rolloutsv1alpha1.Rollout, error)
	Update(ctx context.Context, rollout *rolloutsv1alpha1.Rollout, opts v1.UpdateOptions) (*rolloutsv1alpha1.Rollout, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, rollout *rolloutsv1alpha1.Rollout, opts v1.UpdateOptions) (*rolloutsv1alpha1.Rollout, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*rolloutsv1alpha1.Rollout, error)
	List(ctx context.Context, opts v1.ListOptions) (*rolloutsv1alpha1.RolloutList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *rolloutsv1alpha1.Rollout, err error)
	RolloutExpansion
}

// rollouts implements RolloutInterface
type rollouts struct {
	*gentype.ClientWithList[*rolloutsv1alpha1.Rollout, *rolloutsv1alpha1.RolloutList]
}

// newRollouts returns a Rollouts
func newRollouts(c *ArgoprojV1alpha1Client, namespace string) *rollouts {
	return &rollouts{
		gentype.NewClientWithList[*rolloutsv1alpha1.Rollout, *rolloutsv1alpha1.RolloutList](
			"rollouts",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *rolloutsv1alpha1.Rollout { return &rolloutsv1alpha1.Rollout{} },
			func() *rolloutsv1alpha1.RolloutList { return &rolloutsv1alpha1.RolloutList{} },
		),
	}
}
