coverage:
  status:
    # allow test coverage to drop by 0.1%, assume that it's typically due to CI problems
    patch:
      default:
        threshold: 0.1
    project:
      default:
        threshold: 0.1
ignore:
  - "pkg/apis/rollouts/v1alpha1"
  - "test"
  - "**/*.pb.go"
  - "**/*.pb.gw.go"
  - "**/*generated.go"
  - "**/*generated.deepcopy.go"
  - "**/*_test.go"
  - "pkg/apis/client/.*"
  - "pkg/client/.*"
  - "vendor/.*"
