run:
  timeout: 10m
  modules-download-mode: readonly
issues:
  exclude-dirs:
    - pkg/client
  exclude-files:
    - ".*\\.pb\\.go"
linters-settings:
  goimports:
    local-prefixes: github.com/argoproj/argo-rollouts
linters:
  enable:
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - unconvert
    - unused
  disable-all: true
