version: "2"
run:
  modules-download-mode: readonly
  timeout: 10m
linters:
  default: none
  enable:
    - govet
    - ineffassign
    - misspell
    - unconvert
    - unused
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .*\.pb\.go
      - pkg/client
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/argoproj/argo-rollouts
  exclusions:
    generated: lax
    paths:
      - .*\.pb\.go
      - pkg/client
      - third_party$
      - builtin$
      - examples$
