run:
  deadline: 1m
  skip-files:
    - ".*\\.pb\\.go"
  skip-dirs:
    - pkg/client
  modules-download-mode: readonly
linter-settings:
  goimports:
    local-prefixes: github.com/argoproj/argo-rollouts
linters:
  enable:
    - vet
    - gofmt
    - goimports
    - unused
    - ineffassign
    - unconvert
    - misspell
  disable-all: true
