version: 2
formats: all
mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false
python:
  install:
    - requirements: docs/requirements.txt
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.7"