####################################################################################################
# argo-rollouts-dev
####################################################################################################
FROM golang:1.19-alpine as builder

RUN apk add --no-cache \
    ca-certificates && \
    rm -rf /var/cache/apk/*

FROM gcr.io/distroless/static-debian11

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY rollouts-controller-linux-amd64 /bin/rollouts-controller

# Use numeric user, allows kubernetes to identify this user as being
# non-root when we use a security context with runAsNonRoot: true
USER 999

ENTRYPOINT [ "/bin/rollouts-controller" ]
