// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	v1alpha1 "github.com/argoproj/argo-rollouts/pkg/apis/rollouts/v1alpha1"
	plugin "github.com/argoproj/argo-rollouts/rollout/steps/plugin"
	mock "github.com/stretchr/testify/mock"
)

// StepPlugin is an autogenerated mock type for the StepPlugin type
type StepPlugin struct {
	mock.Mock
}

// Abort provides a mock function with given fields: _a0
func (_m *StepPlugin) Abort(_a0 *v1alpha1.Rollout) (*v1alpha1.StepPluginStatus, error) {
	ret := _m.Called(_a0)

	var r0 *v1alpha1.StepPluginStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(*v1alpha1.Rollout) (*v1alpha1.StepPluginStatus, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*v1alpha1.Rollout) *v1alpha1.StepPluginStatus); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.StepPluginStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(*v1alpha1.Rollout) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Run provides a mock function with given fields: _a0
func (_m *StepPlugin) Run(_a0 *v1alpha1.Rollout) (*v1alpha1.StepPluginStatus, *plugin.StepResult, error) {
	ret := _m.Called(_a0)

	var r0 *v1alpha1.StepPluginStatus
	var r1 *plugin.StepResult
	var r2 error
	if rf, ok := ret.Get(0).(func(*v1alpha1.Rollout) (*v1alpha1.StepPluginStatus, *plugin.StepResult, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*v1alpha1.Rollout) *v1alpha1.StepPluginStatus); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.StepPluginStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(*v1alpha1.Rollout) *plugin.StepResult); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*plugin.StepResult)
		}
	}

	if rf, ok := ret.Get(2).(func(*v1alpha1.Rollout) error); ok {
		r2 = rf(_a0)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Terminate provides a mock function with given fields: _a0
func (_m *StepPlugin) Terminate(_a0 *v1alpha1.Rollout) (*v1alpha1.StepPluginStatus, error) {
	ret := _m.Called(_a0)

	var r0 *v1alpha1.StepPluginStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(*v1alpha1.Rollout) (*v1alpha1.StepPluginStatus, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*v1alpha1.Rollout) *v1alpha1.StepPluginStatus); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.StepPluginStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(*v1alpha1.Rollout) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStepPlugin creates a new instance of StepPlugin. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStepPlugin(t interface {
	mock.TestingT
	Cleanup(func())
}) *StepPlugin {
	mock := &StepPlugin{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
