apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argo-rollouts-notification-configmap.yaml

patches:
  - path: on-rollout-completed.yaml
  - path: on-scaling-replica-set.yaml
  - path: on-rollout-step-completed.yaml
  - path: on-rollout-updated.yaml
  - path: on-rollout-aborted.yaml
  - path: on-rollout-paused.yaml
  - path: on-analysis-run-running.yaml
  - path: on-analysis-run-error.yaml
  - path: on-analysis-run-failed.yaml
