/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	rolloutsv1alpha1 "github.com/argoproj/argo-rollouts/pkg/apis/rollouts/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// AnalysisTemplateLister helps list AnalysisTemplates.
// All objects returned here must be treated as read-only.
type AnalysisTemplateLister interface {
	// List lists all AnalysisTemplates in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*rolloutsv1alpha1.AnalysisTemplate, err error)
	// AnalysisTemplates returns an object that can list and get AnalysisTemplates.
	AnalysisTemplates(namespace string) AnalysisTemplateNamespaceLister
	AnalysisTemplateListerExpansion
}

// analysisTemplateLister implements the AnalysisTemplateLister interface.
type analysisTemplateLister struct {
	listers.ResourceIndexer[*rolloutsv1alpha1.AnalysisTemplate]
}

// NewAnalysisTemplateLister returns a new AnalysisTemplateLister.
func NewAnalysisTemplateLister(indexer cache.Indexer) AnalysisTemplateLister {
	return &analysisTemplateLister{listers.New[*rolloutsv1alpha1.AnalysisTemplate](indexer, rolloutsv1alpha1.Resource("analysistemplate"))}
}

// AnalysisTemplates returns an object that can list and get AnalysisTemplates.
func (s *analysisTemplateLister) AnalysisTemplates(namespace string) AnalysisTemplateNamespaceLister {
	return analysisTemplateNamespaceLister{listers.NewNamespaced[*rolloutsv1alpha1.AnalysisTemplate](s.ResourceIndexer, namespace)}
}

// AnalysisTemplateNamespaceLister helps list and get AnalysisTemplates.
// All objects returned here must be treated as read-only.
type AnalysisTemplateNamespaceLister interface {
	// List lists all AnalysisTemplates in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*rolloutsv1alpha1.AnalysisTemplate, err error)
	// Get retrieves the AnalysisTemplate from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*rolloutsv1alpha1.AnalysisTemplate, error)
	AnalysisTemplateNamespaceListerExpansion
}

// analysisTemplateNamespaceLister implements the AnalysisTemplateNamespaceLister
// interface.
type analysisTemplateNamespaceLister struct {
	listers.ResourceIndexer[*rolloutsv1alpha1.AnalysisTemplate]
}
