/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AnalysisRunListerExpansion allows custom methods to be added to
// AnalysisRunLister.
type AnalysisRunListerExpansion any

// AnalysisRunNamespaceListerExpansion allows custom methods to be added to
// AnalysisRunNamespaceLister.
type AnalysisRunNamespaceListerExpansion any

// AnalysisTemplateListerExpansion allows custom methods to be added to
// AnalysisTemplateLister.
type AnalysisTemplateListerExpansion any

// AnalysisTemplateNamespaceListerExpansion allows custom methods to be added to
// AnalysisTemplateNamespaceLister.
type AnalysisTemplateNamespaceListerExpansion any

// ClusterAnalysisTemplateListerExpansion allows custom methods to be added to
// ClusterAnalysisTemplateLister.
type ClusterAnalysisTemplateListerExpansion any

// ExperimentListerExpansion allows custom methods to be added to
// ExperimentLister.
type ExperimentListerExpansion any

// ExperimentNamespaceListerExpansion allows custom methods to be added to
// ExperimentNamespaceLister.
type ExperimentNamespaceListerExpansion any

// RolloutListerExpansion allows custom methods to be added to
// RolloutLister.
type RolloutListerExpansion any

// RolloutNamespaceListerExpansion allows custom methods to be added to
// RolloutNamespaceLister.
type RolloutNamespaceListerExpansion any
