/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	rolloutsv1alpha1 "github.com/argoproj/argo-rollouts/pkg/apis/rollouts/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// RolloutPluginLister helps list RolloutPlugins.
// All objects returned here must be treated as read-only.
type RolloutPluginLister interface {
	// List lists all RolloutPlugins in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*rolloutsv1alpha1.RolloutPlugin, err error)
	// RolloutPlugins returns an object that can list and get RolloutPlugins.
	RolloutPlugins(namespace string) RolloutPluginNamespaceLister
	RolloutPluginListerExpansion
}

// rolloutPluginLister implements the RolloutPluginLister interface.
type rolloutPluginLister struct {
	listers.ResourceIndexer[*rolloutsv1alpha1.RolloutPlugin]
}

// NewRolloutPluginLister returns a new RolloutPluginLister.
func NewRolloutPluginLister(indexer cache.Indexer) RolloutPluginLister {
	return &rolloutPluginLister{listers.New[*rolloutsv1alpha1.RolloutPlugin](indexer, rolloutsv1alpha1.Resource("rolloutplugin"))}
}

// RolloutPlugins returns an object that can list and get RolloutPlugins.
func (s *rolloutPluginLister) RolloutPlugins(namespace string) RolloutPluginNamespaceLister {
	return rolloutPluginNamespaceLister{listers.NewNamespaced[*rolloutsv1alpha1.RolloutPlugin](s.ResourceIndexer, namespace)}
}

// RolloutPluginNamespaceLister helps list and get RolloutPlugins.
// All objects returned here must be treated as read-only.
type RolloutPluginNamespaceLister interface {
	// List lists all RolloutPlugins in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*rolloutsv1alpha1.RolloutPlugin, err error)
	// Get retrieves the RolloutPlugin from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*rolloutsv1alpha1.RolloutPlugin, error)
	RolloutPluginNamespaceListerExpansion
}

// rolloutPluginNamespaceLister implements the RolloutPluginNamespaceLister
// interface.
type rolloutPluginNamespaceLister struct {
	listers.ResourceIndexer[*rolloutsv1alpha1.RolloutPlugin]
}
