apiVersion: argoproj.io/v1alpha1
kind: Experiment
metadata:
  name: example-experiment
spec:
  duration: 60
  templates:
  - replicas: 1
    name: baseline
    selector:
      matchLabels:
        app: guestbook
        version: v1
    template:
      metadata:
        labels:
          app: guestbook
      spec:
        containers:
        - name: guestbook
          image: gcr.io/heptio-images/ks-guestbook-demo:0.1
          ports:
          - containerPort: 80
  - replicas: 1
    name: canary
    selector:
      matchLabels:
        app: guestbook
        version: v2
    template:
      metadata:
        labels:
          app: guestbook
          version: v2
      spec:
        containers:
        - name: guestbook
          image: gcr.io/heptio-images/ks-guestbook-demo:0.2
          ports:
          - containerPort: 80