apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: example-rollout-bluegreen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        # The image below can be flip from 0.1 to 0.2 
        image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        ports:
        - containerPort: 80
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    blueGreen: 
      activeService: active-service
      previewService: preview-service
      autoPromotionEnabled: false
