apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: example-rollout-bluegreen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: argoproj/rollouts-demo:blue
        ports:
        - containerPort: 80
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    blueGreen: 
      activeService: active-service
      previewService: preview-service
      autoPromotionEnabled: false
