# This example demonstrates a Rollout which starts and finishes analysis at a specific canary step.
# The AnalysisTemplate references an Secret object, which contains an API, token and passes it to a Web metric provider.
#
# Prerequisites: None

apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-secret
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-secret
  template:
    metadata:
      labels:
        app: rollout-secret
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:green
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    canary:
      steps:
      - setWeight: 25
      - analysis:
          templates:
          - templateName: analysis-secret
      - pause: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: token-secret
type: Opaque
data:
  # This API Token is fake. Its value decoded is "test".
  apiToken: dGVzdAo=
---
kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: analysis-secret
spec:
  args:
  - name: api-token
    valueFrom:
      secretKeyRef:
        name: token-secret
        key: apiToken
  metrics:
  - name: webmetric
    successCondition: result == 'It worked!'
    provider:
      web:
      # placeholders are resolved when an AnalysisRun is created
        url: "https://gist.githubusercontent.com/khhirani/2ab11232402518d5277af030dd8916d7/raw/d272f551f2d1806a03974dbaef11dfd55102feea/example.json"
        headers:
        - key: Test
          value: "{{ args.api-token }}"
        jsonPath: "{$.message}"
