# This example demonstrates a Rollout which begins an an experiment at a specified step.
# The rollout will not proceed to the next step until the experiment is completed and successful.
# In this example, the experiment itself starts its own AnalysisRun which is tied to the experiment.
# This is useful for when analysis should be done only during the experimentation phase, but not
# during the regular update of the rollout.
#
# Prerequisites:
# * kubectl apply -f analysis-templates.yaml
#
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-experiment-step
spec:
  replicas: 4
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-experiment-step
  template:
    metadata:
      labels:
        app: rollout-experiment-step
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:blue
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    canary:
      steps:
      - setWeight: 25
      # The second step is the experiment which starts a single canary pod
      - experiment:
          templates:
          - name: canary
            specRef: canary
          # This experiment performs its own analysis by referencing one or more AnalysisTemplates
          # here. The success or failure of these runs will progress or abort the rollout respectively.
          analyses:
          - name: random-fail
            templateName: random-fail
