# This example demonstrates a Rollout which starts and finishes analysis at a specific canary step.
# The AnalysisTemplate references an Secret object, which contains the URL, and passes it to a Web metric provider.
#
# Prerequisites: None

apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-secret
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-secret
  template:
    metadata:
      labels:
        app: rollout-secret
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:blue
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    canary:
      steps:
      - setWeight: 25
      - analysis:
          templates:
          - templateName: analysis-secret
      - pause: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
type: Opaque
data:
  secretUrl: aHR0cHM6Ly9naXN0LmdpdGh1YnVzZXJjb250ZW50LmNvbS9raGhpcmFuaS8yYWIxMTIzMjQwMjUxOGQ1Mjc3YWYwMzBkZDg5MTZkNy9yYXcvZDI3MmY1NTFmMmQxODA2YTAzOTc0ZGJhZWYxMWRmZDU1MTAyZmVlYS9leGFtcGxlLmpzb24=
---
kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: analysis-secret
spec:
  args:
  - name: secret-url
    valueFrom:
      secretKeyRef:
        name: example-secret
        key: secretUrl
  metrics:
  - name: webmetric
    successCondition: result == 'It worked!'
    provider:
      web:
      # placeholders are resolved when an AnalysisRun is created
        url: "{{args.secret-url}}"
        jsonPath: "{$.message}"
