// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	types "github.com/argoproj/argo-rollouts/utils/plugin/types"

	v1alpha1 "github.com/argoproj/argo-rollouts/pkg/apis/rollouts/v1alpha1"
)

// StepPlugin is an autogenerated mock type for the StepPlugin type
type StepPlugin struct {
	mock.Mock
}

// Abort provides a mock function with given fields: _a0, _a1
func (_m *StepPlugin) Abort(_a0 *v1alpha1.Rollout, _a1 *types.RpcStepContext) (types.RpcStepResult, types.RpcError) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Abort")
	}

	var r0 types.RpcStepResult
	var r1 types.RpcError
	if rf, ok := ret.Get(0).(func(*v1alpha1.Rollout, *types.RpcStepContext) (types.RpcStepResult, types.RpcError)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(*v1alpha1.Rollout, *types.RpcStepContext) types.RpcStepResult); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(types.RpcStepResult)
	}

	if rf, ok := ret.Get(1).(func(*v1alpha1.Rollout, *types.RpcStepContext) types.RpcError); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Get(1).(types.RpcError)
	}

	return r0, r1
}

// InitPlugin provides a mock function with given fields:
func (_m *StepPlugin) InitPlugin() types.RpcError {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for InitPlugin")
	}

	var r0 types.RpcError
	if rf, ok := ret.Get(0).(func() types.RpcError); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(types.RpcError)
	}

	return r0
}

// Run provides a mock function with given fields: _a0, _a1
func (_m *StepPlugin) Run(_a0 *v1alpha1.Rollout, _a1 *types.RpcStepContext) (types.RpcStepResult, types.RpcError) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 types.RpcStepResult
	var r1 types.RpcError
	if rf, ok := ret.Get(0).(func(*v1alpha1.Rollout, *types.RpcStepContext) (types.RpcStepResult, types.RpcError)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(*v1alpha1.Rollout, *types.RpcStepContext) types.RpcStepResult); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(types.RpcStepResult)
	}

	if rf, ok := ret.Get(1).(func(*v1alpha1.Rollout, *types.RpcStepContext) types.RpcError); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Get(1).(types.RpcError)
	}

	return r0, r1
}

// Terminate provides a mock function with given fields: _a0, _a1
func (_m *StepPlugin) Terminate(_a0 *v1alpha1.Rollout, _a1 *types.RpcStepContext) (types.RpcStepResult, types.RpcError) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Terminate")
	}

	var r0 types.RpcStepResult
	var r1 types.RpcError
	if rf, ok := ret.Get(0).(func(*v1alpha1.Rollout, *types.RpcStepContext) (types.RpcStepResult, types.RpcError)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(*v1alpha1.Rollout, *types.RpcStepContext) types.RpcStepResult); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(types.RpcStepResult)
	}

	if rf, ok := ret.Get(1).(func(*v1alpha1.Rollout, *types.RpcStepContext) types.RpcError); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Get(1).(types.RpcError)
	}

	return r0, r1
}

// Type provides a mock function with given fields:
func (_m *StepPlugin) Type() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewStepPlugin creates a new instance of StepPlugin. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStepPlugin(t interface {
	mock.TestingT
	Cleanup(func())
}) *StepPlugin {
	mock := &StepPlugin{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
