apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: guestbook
spec:
  selector:
    matchLabels:
      app: guestbook
  volumes:
  - name: config-volume
    configMap:
      name: guestbook-cm
  - name: secret-volume
    secret:
      name: guestbook-secret
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        command:
        - ping $(SERVICE_NAME)
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: guestbook-secret
              key: password
        - name: FOO
          valueFrom:
            configMapKeyRef:
              name: guestbook-cm
              key: foo
  blueGreen:
    activeService: guestbook-svc
