apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: analysistemplates.argoproj.io
spec:
  group: argoproj.io
  names:
    kind: AnalysisTemplate
    listKind: AnalysisTemplateList
    plural: analysistemplates
    singular: analysistemplate
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            metrics:
              items:
                properties:
                  count:
                    format: int32
                    type: integer
                  failFast:
                    type: boolean
                  failureCondition:
                    type: string
                  interval:
                    format: int32
                    type: integer
                  maxConsecutiveErrors:
                    format: int32
                    type: integer
                  maxFailures:
                    format: int32
                    type: integer
                  maxInconclusive:
                    format: int32
                    type: integer
                  name:
                    type: string
                  provider:
                    properties:
                      prometheus:
                        properties:
                          query:
                            type: string
                          server:
                            type: string
                        type: object
                    type: object
                  successCondition:
                    type: string
                required:
                - name
                - provider
                type: object
              type: array
          required:
          - metrics
          type: object
      required:
      - spec
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
