apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/balance: roundrobin
    haproxy.router.openshift.io/disable_cookies: "true"
  labels:
    app: rollouts-demo
  name: main-route
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: stable-service
    weight: 100
