apiVersion: v1
kind: Service
metadata:
  labels:
    app: rollouts-demo
  name: stable-service
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: rollouts-demo
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rollouts-demo
  name: canary-service
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: rollouts-demo 