name: Update Changelog
on:
  release:
    types: [published]
jobs:
  updateChangelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update Changelog
        run: |
          curl -o git-chglog.tar.gz -L https://github.com/git-chglog/git-chglog/releases/download/v0.15.1/git-chglog_0.15.1_darwin_amd64.tar.gz
          tar -zxvf git-chglog
          chmod u+x git-chglog
          ./git-chglog -o CHANGELOG-GENERATED.md
          rm git-chglog
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: update changelog
          title: "docs: Update Changelog"
          body: Update changelog to reflect release changes
          branch: update-changelog
          base: master