name: Publish Extension

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          cd ui && yarn build-extension
